from enum import Enum

class Designation(Enum):
    NA = ""
    UG_STUDENT = "Undergraduate Student"
    PG_STUDENT = "Postgraduate Student"
    PHD = "Ph.D Student"
    POSTDOC = "Post-Doctoral Researcher"
    ASST_PROF = "Assistant Professor"
    ASSCT_PROF = "Associate Professor"
    PROF = "Professor"
    HAG_PROF = "Higher Academic Grade Professor" 

class Degree(Enum):
    NA = ""
    BT = "B.Tech"
    BS = "BS"
    MT = "M.Tech"
    MS = "MS"
    MSR = "MS by Research"
    BTMT = "B.Tech/M.Tech Dual"
    BTMS = "B.Tech/MS Dual"
    BTMBA = "B.Tech/MBA Dual"
    BSMS = "BS/MS Dual"
    BSMT = "BS/M.Tech Dual"
    BSMBA = "BS/MBA Dual"
    MD = "MDes"
    MBA = "MBA"
    MSP = "MS/Ph.D Dual"
    PHD = "Ph.D"

class Department(Enum):
    NA = ""
    AE = "Aerospace Engineering"
    BSBE = "Biological Sciences and Bioengineering"
    CHE = "Chemical Engineering"
    CHM = "Chemistry"
    CE = "Civil Engineering"
    CGS = "Cognitive Sciences"
    CSE = "Computer Science and Engineering"
    DES = "Design"
    ES = "Earth Sciences"
    ECO = "Economics"
    EE = "Electrical Engineering"
    HSS = "Humanities and Social Sciences"
    IS = "Intelligent Systems"
    MSE = "Materials Science and Engineering"
    MTH = "Mathematics"
    ME = "Mechanical Engineering"
    NET = "Nuclear Engineering and Technology"
    DOMS = "Management Sciences"
    PHY = "Physics"
    SPASE = "Space, Planetary and Astronomical Sciences and Engineering"
    SDS = "Statistics and Data Science"
    SEE = "Sustainable Energy Engineering"

IEEE_SKILLS = {}